name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          working-directory: Clean-WEare/app
          run: docker build . --file Dockerfile --tag my-image-name:your-tag
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push your-image-name:your-tag
