name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant
        run: chmod +x Clean-WEare/app/gradlew

      - name: Build
        run: ./gradelw build

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with: 
          image: simvelinov/final_project_docker
          registry: dockerhub.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
