name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build -t your-image-name:your-tag --platform linux/amd64,linux/arm64 -o type=registry -f Clean-WEare/app/Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push your-image-name:your-tag
